on:
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_comment:
  pull_request_review_comment:
    types: created

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'done'
