on:
  workflow_dispatch:
  pull_request:

jobs:
  job-name:
    name: CI (${{ matrix.ref }})
    strategy:
      matrix:
        ref: "${{ github.base_ref || github.ref }}"
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.ref }}"
